language: rust
sudo: required
dist: trusty

env:
  - CODECOV_TOKEN="eb918ac6-42c6-4716-a5b4-cd935cdccd8f"

services:
  - docker

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo build
  - cargo clippy --all-targets
  - cargo test

after_success: |
  docker run --security-opt seccomp=unconfined    \
        -v "$(pwd):/volume"                       \
        xd009642/tarpaulin                        \
        cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage report to codecov.io"
